config/routes.rb
StreamingPastie::Application.routes.draw do
  resources :pasties, except: [:edit], as: "pasties"

  get "images/:id" => "pasties#image", as: "image"

  root 'pasties#index'

end

app/models/pastie.rb
class Pastie
  include Mongoid::Document

  before_create :timestamp
  field :text, type: String
  field :image, type: BSON::Binary
  field :created_at, type: Time

  def timestamp
    self[:created_at] = Time.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/pasties_controller.rb
class PastiesController < ApplicationController
  before_action :set_pastie, only: [:show, :destroy, :update, :image]

  def image
    return send_data "" unless @pastie.image
    send_data @pastie.image.data
  end

  # GET /pasties
  # GET /pasties.json
  def index
    @pasties = Pastie.all.sort {|one, other| other.created_at <=> one.created_at}
  end

  # GET /pasties/1
  # GET /pasties/1.json
  def show
  end

  def update
    @pastie.image = BSON::Binary.new(params["file"].tempfile.read) if params["file"]

    respond_to do |format|
      if @pastie.save!
        format.html { redirect_to @pastie, notice: 'Pastie was successfully updated.' }
        format.json { render action: 'show', status: :created, location: @pastie }
      else
        format.html { render action: 'new' }
        format.json { render json: @pastie.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /pasties/new
  def new
    @pastie = Pastie.new
  end

  # POST /pasties
  # POST /pasties.json
  def create
    @pastie = Pastie.new(pastie_params)
    @pastie.image = BSON::Binary.new(params["pastie"]["image"].read) if params["pastie"]["image"]

    respond_to do |format|
      if @pastie.save!
        format.html { redirect_to @pastie, notice: 'Pastie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pastie }
      else
        format.html { render action: 'new' }
        format.json { render json: @pastie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pasties/1
  # DELETE /pasties/1.json
  def destroy
    @pastie.destroy
    respond_to do |format|
      format.html { redirect_to pasties_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pastie
    @pastie = Pastie.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pastie_params
    params.require(:pastie).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pasties_helper.rb
module PastiesHelper
  def image_url_or_nil pastie
    return image_url(pastie) if pastie.image

    nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreamingPastie</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pasties/_form.html.haml
= form_for @pastie do |f|
  - if @pastie.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pastie.errors.count, "error")} prohibited this pastie from being saved:"
      %ul
        - @pastie.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/pasties/edit.html.haml
%h1 Editing pastie

= render 'form'

= link_to 'Show', @pastie
\|
= link_to 'Back', pasties_path

app/views/pasties/index.html.haml
%h1 Listing pasties

%table
  %tr
    %th Text
    %th Image
    %th
    %th
    %th

  - @pasties.each do |pastie|
    %tr
      %td= pastie.text
      %td= pastie.image
      %td= link_to 'Show', pastie
      %td= link_to 'Destroy', pastie, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pastie', new_pastie_path

app/views/pasties/new.html.haml
%h1 New pastie

= render 'form'

= link_to 'Back', pasties_path

app/views/pasties/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @pastie.id
%p
  %b Text:
  = @pastie.text
%p
  %b Created at:
  = "#{time_ago_in_words @pastie.created_at} ago"
%p
  %b Image:
  = image_tag image_path(@pastie)

= link_to 'Back', pasties_path